name: Build and Push React Docker Image

on:
  push:
    paths:
      - 'assignment1/react-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t praneetha2699/react-frontend ./assignment1/react-frontend

    - name: Push Docker image
      run: docker push praneetha2699/react-frontend
